package org.pp.modules.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApplication<M extends BaseApplication<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 应用名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 应用名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 应用地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 应用地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 应用类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 应用类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 创建时间
	 */
	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getAddTime() {
		return get("add_time");
	}

	/**
	 * 应用说明
	 */
	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}
	
	/**
	 * 应用说明
	 */
	public java.lang.String getComment() {
		return getStr("comment");
	}

	/**
	 * 排序
	 */
	public void setListSort(java.lang.Integer listSort) {
		set("list_sort", listSort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getListSort() {
		return getInt("list_sort");
	}

	/**
	 * 图标
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
