package org.pp.modules.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserLogin<M extends BaseUserLogin<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 用户
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * IP地址
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * IP地址
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * Session
	 */
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}
	
	/**
	 * Session
	 */
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}

	/**
	 * 登录时间
	 */
	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}
	
	/**
	 * 登录时间
	 */
	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	/**
	 * 退出时间
	 */
	public void setLogoutTime(java.util.Date logoutTime) {
		set("logout_time", logoutTime);
	}
	
	/**
	 * 退出时间
	 */
	public java.util.Date getLogoutTime() {
		return get("logout_time");
	}

}
