package org.pp.modules.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDict<M extends BaseDict<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 上级
	 */
	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	/**
	 * 上级
	 */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 代码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 排序
	 */
	public void setListSort(java.lang.Integer listSort) {
		set("list_sort", listSort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getListSort() {
		return getInt("list_sort");
	}

}
