package org.pp.modules.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 操作用户
	 */
	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	/**
	 * 操作用户
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 操作动作
	 */
	public void setActionId(java.lang.Integer actionId) {
		set("action_id", actionId);
	}
	
	/**
	 * 操作动作
	 */
	public java.lang.Integer getActionId() {
		return getInt("action_id");
	}

	/**
	 * 上传时间
	 */
	public void setActionTime(java.util.Date actionTime) {
		set("action_time", actionTime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getActionTime() {
		return get("action_time");
	}

	/**
	 * 参数
	 */
	public void setParam(java.lang.String param) {
		set("param", param);
	}
	
	/**
	 * 参数
	 */
	public java.lang.String getParam() {
		return getStr("param");
	}

	/**
	 * 排序
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 排序
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

}
