package org.pp.modules.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 发布人
	 */
	public void setAddUserId(java.lang.Integer addUserId) {
		set("add_user_id", addUserId);
	}
	
	/**
	 * 发布人
	 */
	public java.lang.Integer getAddUserId() {
		return getInt("add_user_id");
	}

	/**
	 * 发布时间
	 */
	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}
	
	/**
	 * 发布时间
	 */
	public java.util.Date getAddTime() {
		return get("add_time");
	}

	/**
	 * 阅读量
	 */
	public void setReadCount(java.lang.Long readCount) {
		set("read_count", readCount);
	}
	
	/**
	 * 阅读量
	 */
	public java.lang.Long getReadCount() {
		return getLong("read_count");
	}

}
