package org.pp.modules.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 文件名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 扩展名
	 */
	public void setExts(java.lang.String exts) {
		set("exts", exts);
	}
	
	/**
	 * 扩展名
	 */
	public java.lang.String getExts() {
		return getStr("exts");
	}

	/**
	 * 唯一标识
	 */
	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	/**
	 * 唯一标识
	 */
	public java.lang.String getMd5() {
		return getStr("md5");
	}

	/**
	 * 保存路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 保存路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 上传用户
	 */
	public void setUploadUserId(java.lang.Integer uploadUserId) {
		set("upload_user_id", uploadUserId);
	}
	
	/**
	 * 上传用户
	 */
	public java.lang.Integer getUploadUserId() {
		return getInt("upload_user_id");
	}

	/**
	 * 上传时间
	 */
	public void setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getUploadTime() {
		return get("upload_time");
	}

	/**
	 * 文件大小
	 */
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	/**
	 * 文件大小
	 */
	public java.lang.Long getSize() {
		return getLong("size");
	}

	/**
	 * 封面
	 */
	public void setCover(java.lang.String cover) {
		set("cover", cover);
	}
	
	/**
	 * 封面
	 */
	public java.lang.String getCover() {
		return getStr("cover");
	}

	/**
	 * 长度
	 */
	public void setLength(java.lang.Integer length) {
		set("length", length);
	}
	
	/**
	 * 长度
	 */
	public java.lang.Integer getLength() {
		return getInt("length");
	}

	/**
	 * 预览文件
	 */
	public void setPreFile(java.lang.String preFile) {
		set("pre_file", preFile);
	}
	
	/**
	 * 预览文件
	 */
	public java.lang.String getPreFile() {
		return getStr("pre_file");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
