package org.pp.modules.sys.model;

import org.pp.modules.sys.model.UserLogin;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_action", "id", Action.class);
		arp.addMapping("sys_application", "id", Application.class);
		arp.addMapping("sys_category", "id", Category.class);
		arp.addMapping("sys_config", "id", Config.class);
		arp.addMapping("sys_department", "id", Department.class);
		arp.addMapping("sys_dict", "id", Dict.class);
		arp.addMapping("sys_file", "id", File.class);
		arp.addMapping("sys_log", "id", Log.class);
		arp.addMapping("sys_menu", "id", Menu.class);
		arp.addMapping("sys_notice", "id", Notice.class);
		arp.addMapping("sys_role", "id", Role.class);
		arp.addMapping("sys_token", "id", Token.class);
		arp.addMapping("sys_user", "id", User.class);
		arp.addMapping("sys_user_login", "id", UserLogin.class);
	}
}

