package org.pp.modules.sys.model;

import org.pp.modules.sys.base.BaseApplication;

import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Application extends BaseApplication<Application> {

	public String getIcon(String defaults) {
		String icon = getIcon();
		if(StrKit.isBlank(icon)) {
			icon = defaults;
		}
		if(icon.startsWith("fa-")) {
			icon = icon.substring(3);
		}
		return icon;
	}
}
