package org.pp.modules.sys.model;

import org.pp.modules.sys.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	
}
