package org.pp.modules.sys.model;

import org.pp.modules.sys.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	
}
