package org.pp.modules.sys.model;

import org.pp.modules.sys.base.BaseFile;
import org.pp.modules.sys.service.UserService;

import com.jfinal.aop.Aop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	private User user;

	public User getUser() {
		if(user == null && getUploadUserId() != null) {
			user = Aop.get(UserService.class).findCache(getUploadUserId());
		}
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	/**
	 * 判断当前文档是否为PDF格式
	 * @return boolean
	 */
	public boolean isPdf() {
		return getExts().equalsIgnoreCase("pdf");
	}
	/**
	 * 判断当前文档是否为图片格式
	 * @return boolean
	 */
	public boolean isImage() {
		String exts[] = {"jpg", "png", "gif", "jpeg"};
		for(String e:exts) {
			if(getExts().equalsIgnoreCase(e)) return true;
		}
		return false;
	}
	
	/**
	 * 判断当前文档是否为视频格式
	 * @return boolean
	 */
	public boolean isVideo() {
		String exts[] = {"wmv", "avi", "mp4", "3gp", "rm", "rmvb", "mkv", "flv", "asf", "mov", "3gp"};
		for(String e:exts) {
			if(getExts().equalsIgnoreCase(e)) return true;
		}
		return false;
	}
}
