package org.pp.modules.sys.model;

import org.pp.modules.sys.base.BaseNotice;
import org.pp.modules.sys.service.UserService;

import com.jfinal.aop.Aop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {

	private User user;
	
	public User getUser() {
		if(user == null && getAddUserId() != null) {
			user = Aop.get(UserService.class).findCache(getAddUserId());
		}
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}
