package org.pp.modules.dev.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChart<M extends BaseChart<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 分类
	 */
	public void setCateId(java.lang.Integer cateId) {
		set("cate_id", cateId);
	}
	
	/**
	 * 分类
	 */
	public java.lang.Integer getCateId() {
		return getInt("cate_id");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 代码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 数据源
	 */
	public void setDsId(java.lang.Integer dsId) {
		set("ds_id", dsId);
	}
	
	/**
	 * 数据源
	 */
	public java.lang.Integer getDsId() {
		return getInt("ds_id");
	}

	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 说明
	 */
	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}
	
	/**
	 * 说明
	 */
	public java.lang.String getComment() {
		return getStr("comment");
	}

	/**
	 * 排序
	 */
	public void setListSort(java.lang.Integer listSort) {
		set("list_sort", listSort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getListSort() {
		return getInt("list_sort");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
