package org.pp.modules.dev.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseField<M extends BaseField<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 所属模型
	 */
	public void setModelId(java.lang.Long modelId) {
		set("model_id", modelId);
	}
	
	/**
	 * 所属模型
	 */
	public java.lang.Long getModelId() {
		return getLong("model_id");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 代码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 数据库类型
	 */
	public void setDbType(java.lang.String dbType) {
		set("db_type", dbType);
	}
	
	/**
	 * 数据库类型
	 */
	public java.lang.String getDbType() {
		return getStr("db_type");
	}

	/**
	 * 业务类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 业务类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 长度
	 */
	public void setLen(java.lang.Integer length) {
		set("len", length);
	}
	
	/**
	 * 长度
	 */
	public java.lang.Integer getLen() {
		return getInt("len");
	}

	/**
	 * 缩放
	 */
	public void setScale(java.lang.Integer scale) {
		set("scale", scale);
	}
	
	/**
	 * 缩放
	 */
	public java.lang.Integer getScale() {
		return getInt("scale");
	}

	/**
	 * 空值
	 */
	public void setNullable(java.lang.String nullable) {
		set("nullable", nullable);
	}
	
	/**
	 * 空值
	 */
	public java.lang.String getNullable() {
		return getStr("nullable");
	}

	/**
	 * 默认值
	 */
	public void setDefaults(java.lang.String defaults) {
		set("defaults", defaults);
	}
	
	/**
	 * 默认值
	 */
	public java.lang.String getDefaults() {
		return getStr("defaults");
	}

	/**
	 * 自动计算公式
	 */
	public void setCalculate(java.lang.String calculate) {
		set("calculate", calculate);
	}
	
	/**
	 * 自动计算公式
	 */
	public java.lang.String getCalculate() {
		return getStr("calculate");
	}

	/**
	 * 参数
	 */
	public void setParam(java.lang.String param) {
		set("param", param);
	}
	
	/**
	 * 参数
	 */
	public java.lang.String getParam() {
		return getStr("param");
	}
	/**
	 * 排序
	 */
	public void setListSort(java.lang.Integer listSort) {
		set("list_sort", listSort);
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getListSort() {
		return getInt("list_sort");
	}
}
