package org.pp.modules.dev.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModule<M extends BaseModule<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 代码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
