package org.pp.modules.dev.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModels<M extends BaseModels<M>> extends Model<M> implements IBean {

	/**
	 * 自增长主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增长主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 所属模块
	 */
	public void setModuleId(java.lang.Long moduleId) {
		set("module_id", moduleId);
	}
	
	/**
	 * 所属模块
	 */
	public java.lang.Long getModuleId() {
		return getLong("module_id");
	}

	/**
	 * 数据表
	 */
	public void setTables(java.lang.String tables) {
		set("tables", tables);
	}
	
	/**
	 * 数据表
	 */
	public java.lang.String getTables() {
		return getStr("tables");
	}

	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 代码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 代码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 名称
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	/**
	 * 数据主键字段
	 */
	public void setPkField(java.lang.String pkField) {
		set("pk_field", pkField);
	}
	
	/**
	 * 数据主键字段
	 */
	public java.lang.String getPkField() {
		return getStr("pk_field");
	}
	
}
