package org.pp.modules.dev.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dev_field", "id", Field.class);
		arp.addMapping("dev_models", "id", Models.class);
		arp.addMapping("dev_module", "id", Module.class);
		arp.addMapping("dev_validation", "id", Validation.class);
		arp.addMapping("dev_chart", "id", Chart.class);
		arp.addMapping("dev_dataset", "id", Dataset.class);
		
	}
}

